### ISSUE TITLE
Create/update Models

### ISSUE THREAD

**Issue by BuckyTheBoss** [MrAch26/acting_project#1]
Accounts:
    Profile
        is_actor 

Main:
    JobOpp
        owner = profile
        actors = profiles
   
WorkHistory(tv/movie/misc)

    
Chat:
       tbd

**Comment by MrAch26** [comment]
Main:
JobOpp
owner = profile
actors = profiles

Chat:
tbd...

**Comment by MrAch26** [comment]
IF POSSIBLE CREATE CHAT

**Comment by MrAch26** [comment]
moved soime issues
