### ISSUE TITLE
home search filter ...

### ISSUE THREAD

**Issue by MrAch26** [MrAch26/acting_project#9]
Created a search filter in home page to get specific job opportunities

example : 
- filter for french speaking job
- for skin color
- for age range
- location
- compensation (paid or not)
- is_home from home or not

**Comment by BuckyTheBoss** [comment]
check this out https://django-filter.readthedocs.io/en/stable/

**Comment by MrAch26** [comment]
https://www.youtube.com/watch?v=nle3u6Ww6Xk

**Comment by MrAch26** [comment]
yes done :) 🥇
